networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - default
